// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqd9eWo0zUiyx1wJnldBYwgqeRFuBXErQ',
    appId: '1:704671874624:web:a07e1c801cc77fc1d969a5',
    messagingSenderId: '704671874624',
    projectId: 'amar-hisab-ec7e5',
    authDomain: 'amar-hisab-ec7e5.firebaseapp.com',
    storageBucket: 'amar-hisab-ec7e5.firebasestorage.app',
    measurementId: 'G-JGLXLCEB3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyCnM_0Dppx3vnewmnbjbA5sFRCBm-vGs',
    appId: '1:704671874624:android:6880273775c4d799d969a5',
    messagingSenderId: '704671874624',
    projectId: 'amar-hisab-ec7e5',
    storageBucket: 'amar-hisab-ec7e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXfVS64sshCupAEl7-p5_pupYjbnospW8',
    appId: '1:704671874624:ios:6f3589a8c93e17e5d969a5',
    messagingSenderId: '704671874624',
    projectId: 'amar-hisab-ec7e5',
    storageBucket: 'amar-hisab-ec7e5.firebasestorage.app',
    iosBundleId: 'com.amarhisab.amarHisab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXfVS64sshCupAEl7-p5_pupYjbnospW8',
    appId: '1:704671874624:ios:6f3589a8c93e17e5d969a5',
    messagingSenderId: '704671874624',
    projectId: 'amar-hisab-ec7e5',
    storageBucket: 'amar-hisab-ec7e5.firebasestorage.app',
    iosBundleId: 'com.amarhisab.amarHisab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqd9eWo0zUiyx1wJnldBYwgqeRFuBXErQ',
    appId: '1:704671874624:web:13524b53e2daea61d969a5',
    messagingSenderId: '704671874624',
    projectId: 'amar-hisab-ec7e5',
    authDomain: 'amar-hisab-ec7e5.firebaseapp.com',
    storageBucket: 'amar-hisab-ec7e5.firebasestorage.app',
    measurementId: 'G-58C16BZ7M3',
  );
}
